In [1]:
m1 = [[1,2,3],
        [6, -4, -9],
        [3,6,9]]

m2 = [[6,9,3],
        [1,-1,1],
        [0, 9, 11]]

### 1. Write a Python Program to Add Two Matrices?

In [2]:
def add_mat(m1,m2):
    output = []
    for i in range(len(m1)):
        add_mat = []
        for j in range(len(m1)):
            add_mat.append(m1[i][j] +m2[i][j])
        output.append(add_mat)
    print(output)

In [3]:
add_mat(m1,m2)

[[7, 11, 6], [7, -5, -8], [3, 15, 20]]


### 2. Write a Python Program to Multiply Two Matrices?

In [4]:
A = [[12, 7, 3],
    [4, 5, 6],
    [7, 8, 9]]

B = [[5, 8, 1, 2],
    [6, 7, 3, 0],
    [4, 5, 9, 1]]

In [5]:
import numpy as np
multiply = np.dot(A,B)
for i in multiply:
    print(i)

[114 160  60  27]
[74 97 73 14]
[119 157 112  23]


### 3. Write a Python Program to Transpose a Matrix?

In [6]:

X = [[12,7],
    [4 ,5],
    [3 ,8]]

result = [[0,0,0],
         [0,0,0]]

for i in range(len(X)):
    for j in range(len(X[0])):
        result[j][i] = X[i][j]
for i in result:
    print(i)

[12, 4, 3]
[7, 5, 8]


### 4. Write a Python Program to Sort Words in Alphabetic Order?

In [7]:
sentence = input('Enter the sentence: ')
words = []
for i in sentence.split():
    words.append(i.lower())
words.sort()

for i in words:
    print(i,end =" ")


Enter the sentence: My name is rajbir
is my name rajbir 

### 5. Write a Python Program to Remove Punctuation From a String?

In [8]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

def remove_punc():
    output = ""
    string = input("enter the string:  ")
    for i in string:
        if i not in punctuations:
            output = output +i

    return output 
            
    
remove_punc()


enter the string:  Hello my dear friend !!! {tere jaisa yaar kaha}


'Hello my dear friend  tere jaisa yaar kaha'